spring.application.name=MobilHomyServer

#Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MOBILHOMY;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=QuidNovice

#Détail des requêtes pour le développement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

#JWT
app.jwt.secret=5a5965494c20266b4b5571717e29413f2156555621515a205f7c204376
app.jwt.expiration=86400000

logging.level.org.springframework.security=TRACE